development:
  adapter: mysql
  database: eventstreams_development
  username: root
  password: 
  pool: 5
  host: 127.0.0.1

test:
  adapter: mysql
  database: eventstreams_test
  username: root
  password: 
  pool: 5
  host: 127.0.0.1

cucumber:
  adapter: mysql
  database: eventstreams_test
  username: root
  password: 
  pool: 5
  host: 127.0.0.1
  